spring:
  main:
    lazy-initialization: true
  # Настройка для базы H2
    #  spring.hibernate.hbm2ddl.auto=create-drop
  dataSource:
    url: jdbc:postgresql://192.168.1.20:5432/animal
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  flyway:
    enabled: true
    #        generate_statistics: true
  jpa:
    # Hibernate ddl auto (create, create-drop, validate, update)
    #hibernate.ddl-auto: validate
    #hibernate.ddl-auto: create
    properties:
      #      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
#      hibernate.use_sql_comments: true

server:
  servlet:
    context-path: /api
