spring:
  main:
    lazy-initialization: true
  # Настройка для базы H2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
    #  spring.hibernate.hbm2ddl.auto=create-drop
  dataSource:
    url: jdbc:h2:mem:animal
    driverClassName: org.h2.Driver
    username: sa
    password:
  # Hibernate ddl auto (create, create-drop, validate, update)
  hibernate:
    ddl-auto: create-drop
    dialect: org.hibernate.dialect.H2Dialect
    #        generate_statistics: true
  jpa:
    # show SQL statements in console.
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: /api
